version: "3.8"

services:

  mysql:
    image: mysql:8.0.44
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ims_db
      MYSQL_USER: ims_user
      MYSQL_PASSWORD: ims_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: ims-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ims_db
      SPRING_DATASOURCE_USERNAME: ims_user
      SPRING_DATASOURCE_PASSWORD: ims_pass

volumes:
  mysql_data: